### ISSUE TITLE
¿Caso de test duplicado?

### ISSUE THREAD

**Issue by SUPERNOOB20** [tomas-ezama/TP-Funcional-Haskell-Wololo#1]
Revisar ln89, 90 en nuestrosTests.hs:

 "tieneUnSeguidorFiel 4: Existe un usuario u2 al que le gustan algunas publicaciones de u, y no le gusta ninguna otra publicación" ~: tieneUnSeguidorFiel **redA u2** ~?= False,
    "tieneUnSeguidorFiel 5: Existe un usuario u2 al que le gustan algunas publicaciones de u, y tambièn le gustan otras publicaciones de otros usuarios (distintos a u y u2)" ~: tieneUnSeguidorFiel **redA u2** ~?= False

Vemos a ojo que no existe ninguna relación de fuerzas entre el Caso 4 y el Caso 5, entonces están bien planteados. Sin embargo, yo armé los tests con la misma red de ejemplo, ¿tiene sentido esto? Si no, queda pendiente, de ser necesario, armar dos redes distintas redP1 redP2 que solucionen esto

**Comment by SUPERNOOB20** [comment]
Planteo una posible solución, que podría ser:

"tieneUnSeguidorFiel 4: Existe un usuario u2 al que le gustan algunas publicaciones de u, y no le gusta ninguna otra publicación" ~: tieneUnSeguidorFiel redA u2 ~?= False,
"tieneUnSeguidorFiel 5: Existe un usuario u2 al que le gustan algunas publicaciones de u, y tambièn le gustan otras publicaciones de otros usuarios (distintos a u y u2)" ~: **True**


Es decir que el caso 5 se plantea pero no se testea, ya que si bien forma parte de la partición de categorías, el caso 4 ya nos lo resuelve.

**Comment by Romelai28** [comment]
La idea de plantear 4 y 5 es que es test de caja negra, no sabemos como esta implementado, podría venir alguien que puso un == comparando las listas y de bien en el caso 4 pero mal en el caso 5. Como mucho si queremos hacer menos test tiene sentido testear el caso 5 pero no el 4 pero nunca al revez. Aunque por mi testearia ambos

No revise todavía que es tu redA pero si estas pasando los mismos parametros significa que no estas siguiendo lo pedido porque son casos excluyentes el que "no le gusta ninguna otra publicación" y "tambien le gustan otras publicaciones"

En cuanto al segundo comentario, esta solución es falsa. No debe devolver True el caso 5 porque justamente dice que "le gustan algunas publicaciones de u (no todas)" y tieneUnSeguidorFiel es verdadera si y solo si le gustan todas las publicaciones de u"

**Comment by SUPERNOOB20** [comment]
Buenas,
la idea del "True" era que el test devolviera True, sin pasar por el resultado del ejercicio que sí es False como indicaste
No son excluyentes el caso 4 y el caso 5 ya que me describe características de un usuario en específico y no de la red entera. Por ejemplo redA u2 puede estar mirando a u1 en el caso 4 y redA u2 puede estar mirando a u3 en el caso 5. De todas formas, ya lo arreglé. Gracias por el feedback.
