### ISSUE TITLE
Test con operaciones booleanas

### ISSUE THREAD

**Issue by SUPERNOOB20** [tomas-ezama/TP-Funcional-Haskell-Wololo#3]
En Ln 45, nuestrosTests.hs:

![image](https://github.com/tomas-ezama/TP-Funcional-Haskell-Wololo/assets/82103347/6a42bd4d-26bc-4ce4-a8b7-b2451bea675a)
![image](https://github.com/tomas-ezama/TP-Funcional-Haskell-Wololo/assets/82103347/1e860889-6ac2-41c0-b58b-9422b9709a6e)

La expresión "(u1 || u2 || u3)" del lado derecho no es válida a la hora de comparar con el lado izquierdo
Necesitamos encontrar una forma de que cualquiera de esos 3 valores, u1, u2, u3, sean válidos para este caso de test.
:godmode: :feelsgood: :trollface:

**Comment by Romelai28** [comment]
HUnit te permite testear expresiones con or con expectAny, en pruebas.hs habia usado así:
![image](https://github.com/tomas-ezama/TP-Funcional-Haskell-Wololo/assets/100548962/894f05af-f823-4e8f-bd22-6c92bdcd4297)

**Comment by SUPERNOOB20** [comment]
![image](https://github.com/tomas-ezama/TP-Funcional-Haskell-Wololo/assets/82103347/42b7a208-e9d7-43b6-863a-b0964a02146f)
Buenísimo, ya lo pude arreglar con el ejemplo que hiciste vos, ¡gracias!
